---
abstract: 'Prevent trailing whitespace from being committed.'
author:
  - 'Ben Arwin <barwin@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Test::Exception: 0
  Test::FailWarnings: 0
  Test::Git: 0
  Test::More: 0.94
  Test::Type: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-GitHooks-Plugin-PreventTrailingWhitespace
provides:
  App::GitHooks::Plugin::PreventTrailingWhitespace:
    file: lib/App/GitHooks/Plugin/PreventTrailingWhitespace.pm
    version: v1.0.1
requires:
  App::GitHooks: 0
  Carp: 0
  Data::Validate::Type: 0
  File::Slurp: 0
  perl: 5.01
resources:
  bugtracker: https://github.com/barwin/App-GitHooks-Plugin-PreventTrailingWhitespace/issues
  homepage: https://metacpan.org/release/App-GitHooks-Plugin-PreventTrailingWhitespace
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/barwin/App-GitHooks-Plugin-PreventTrailingWhitespace
version: v1.0.1
